### PR TITLE
copy Waldo's explanation of some terminology from issue #494 into the docs

### PR DESCRIPTION
**Pull request by JoshData**
Thanks for the response on https://github.com/statedecoded/statedecoded/issues/494. I thought it would be useful for others to read here.

### CODE REVIEW

**Comment by waldoj** [comment]
Great! I'll eventually move this section over to establish a new page in the docs, an introduction to legal codes. The most frequent type of question that I get is from people who simply don't understand legal codes, which I _totally_ get, because that's where I was about four years ago.

Thanks for teasing that documentation out of me, Josh. :)

**Comment by JoshData** [comment]
FWIW, I think it's good to keep it close to where the terminology is used. Or, if you make a new intro, keep some or all of this explanation on the XML format page too.

**Comment by waldoj** [comment]
Well, the terminology is used all over the place. :) I think there ought to be brief explanations the first time that each such word is used on each portion of the documentation, with links to the detailed explanation on the "introduction to legal codes" chapter.

**Comment by JoshData** [comment]
Perhaps a "definitions" page. You need meta-State Decoded.

**Comment by waldoj** [comment]
:)

**Pull request merged**
